default: &default
  adapter: postgresql
  encoding: unicode
  username: danhack
  password: abc123
  host: localhost
  pool: 5

development:
  <<: *default
  database: homemade_broadcast_development

test:
  <<: *default
  database: homemade_broadcast_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: homemade_broadcast_production
  username: homemade_broadcast
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
